- name : RoboShop Project - frontend
  hosts: all
  become: true
  tasks:
    - name: install nginx
      ansible.builtin.yum:
        name: nginx
        state: installed
    - name: copy Roboshop Configuration
      ansible.builtin.copy:


